Initial version of Gem
budacom/activeadmin_resource pull request #1
Opened 2018-03-27 21:15 UTC by vreyn

This PR creates the initial version of this gem, with the following features:
 - Patch for ActiveAdmin::Filters::FormtasticAddons module
 - Patch for ActiveAdmin::Helpers::Collection module
 - Patch for ActiveResource::Connection class to support signed requests
 - ActiveAdminResource::Base class to be extended when defining ActiveResource models that need to be admined with ActiveAdmin.

All of the above are crammed together in one file for now, because of lack of knowledge from the author on how to include external files in Ruby :S 
Comments to the PR explaining how to do this and other Gem creation best practices are welcomed :)

2018-03-27 21:27 UTC, vanhalt commented on README.md
> -    "4799c30a437de97cf4c94a0a224d51cc"
Creo que deberíamos reescribir la historia de commits y eliminar este. Por si algún día hacemos esta gema pública o incluso por uso interno.

2018-03-28 02:09 UTC, iobaixas requested changes
@vreyn you could put each class in a separate file under the `/lib/active_admin_resource/*` directory. Then you can require them from the main `/lib/active_admin_resource.rb` file.

2018-03-28 12:40 UTC, alejandroechev commented on README.md
> -    "4799c30a437de97cf4c94a0a224d51cc"
Gracias Rafa, ocupé esta herramienta para eliminar los key de la historia https://rtyley.github.io/bfg-repo-cleaner/
Aparentemente funcionó, los reemplazo por REMOVED (aunque igual aparece aquí en este comentario el key)

2018-03-28 13:02 UTC, alejandroechev commented
@iobaixas Thanks, I pushed a cleaned-up version with each patch / class in a separate file. For some reason this didnt work at some point for me because of some Docker cache issues and I gave up, but know it worked :)

2018-03-29 13:06 UTC, iobaixas commented on lib/active_admin_resource/connection_patch.rb
> +ActiveResource::Connection.prepend(ConnectionExtensions)
@vreyn i think that 'setup' code like this line should be called in the main library file or in a 'railties' file and not in the 'class file'.

2018-03-29 16:21 UTC, alejandroechev commented on lib/active_admin_resource/connection_patch.rb
> +ActiveResource::Connection.prepend(ConnectionExtensions)
Ok, I moved this line to the main lib file

2018-04-03 21:34 UTC, alejandroechev commented on lib/active_admin_resource/connection_patch.rb
> +ActiveResource::Connection.prepend(ConnectionExtensions)
I moved the setup code to a railtie file now.

2018-04-10 16:20 UTC, iobaixas approved these changes

2018-04-10 20:37 UTC, merged